name: 'Cypress E2E Testing'

trigger:
- master
- dev

schedules:
- cron: "0 6 * * *"
  displayName: Each morning at 6am
  branches:
    include:
    - dev

variables:
- ${{ if eq(variables['build.SourceBranchName'], 'master') }}:
  - group: estruyf-master
- ${{ if ne(variables['build.SourceBranchName'], 'master') }}:
  - group: estruyf-dev
- name: npm_config_cache
  value: $(Pipeline.Workspace)/.npm
- name: CYPRESS_CACHE_FOLDER # Overrides the default cache location
  value: $(Pipeline.Workspace)/.cache/Cypress

stages:
- stage: e2e_testing_stage_chrome
  displayName: 'Chrome E2E Testing'
  jobs:
  - job: e2e_testing_job_chrome
    displayName: 'Run E2E in Chrome'
    pool:
      vmImage: macos-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: chrome

- stage: e2e_testing_stage_firefox
  displayName: 'Firefox E2E Testing'
  dependsOn: []
  jobs:
  - job: e2e_testing_job_firefox
    displayName: 'Run E2E in Firefox'
    pool:
      vmImage: macos-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: firefox
          
- stage: e2e_testing_stage_edge
  displayName: 'Edge E2E Testing'
  dependsOn: []
  jobs:  
  - job: e2e_testing_job_edge
    displayName: 'Run E2E in Edge'
    pool:
      vmImage: macos-latest
    steps:
      - template: devops/e2e.testing.yml
        parameters:
          browserType: edge
          